server:
  port: 7070
  servlet:
    context-path: /market-auth
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:market-auth;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
jwt:
  secret: fnmlaskfnaljkfhnalkfbnalkjfnbaklfnaklfnalksnfasklfnalskfn
  lifetime: 360000000

